import{COUNT,level,rotate,connected,validateSave}from './engine.js';
import{platform,embedded}from './platform.js';
const $=id=>document.getElementById(id),chapters=['First light','Wild roots','Moon garden','The luminous grove'],names=['A spark awakens','Little by little','Roots of wonder','A quiet connection','Follow the light','First bloom','Into the green','Winding paths','A new leaf','Tangled together','Softly growing','Wild at heart','Moonlit branches','Midnight petals','A silver thread','The hidden garden','Under the stars','Night bloom','A deeper glow','Golden roots','All connected','A world of light','Almost home','The grove awakens'];
let save,puzzle,tiles,moves=0,hints=0,history=[],won=false,paused=false,systemPaused=false,sound=embedded,audioAllowed=true,context,highlight=-1;
const board=$('board'),dialog=$('dialog');
function persist(){if(!save||!tiles)return Promise.resolve(false);save.active={tiles:[...tiles],moves,hints};return platform.save(save).then(ok=>{if(!ok&&!systemPaused)$('completed').textContent='Progress could not be saved on this device';});}
function tone(win=false){if(!sound||!audioAllowed||paused||systemPaused)return;try{context??=new(window.AudioContext||window.webkitAudioContext)();context.resume();const notes=win?[523.25,659.25,783.99]:[260+connected(tiles,puzzle.n,puzzle.source).size*15];notes.forEach((hz,i)=>{const o=context.createOscillator(),g=context.createGain(),t=context.currentTime+i*.11;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.07,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.3);o.connect(g);g.connect(context.destination);o.start(t);o.stop(t+.32);});}catch{}}
function tileArt(mask,i){let paths='';const ends=[[50,0],[100,50],[50,100],[0,50]];for(let d=0;d<4;d++)if(mask&(1<<d))paths+=`M50 50 L${ends[d][0]} ${ends[d][1]} `;const leaf=(mask&(mask-1))===0;let center=i===puzzle.source?'<circle cx="50" cy="50" r="17" fill="#f2cd83"/><circle cx="50" cy="50" r="24" fill="none" stroke="currentColor" stroke-width="1" stroke-dasharray="2 5"/><path d="M50 40v20m-10-10h20" stroke="#615a36" stroke-width="2"/>':leaf?'<g fill="currentColor"><ellipse cx="50" cy="41" rx="5" ry="10"/><ellipse cx="50" cy="59" rx="5" ry="10"/><ellipse cx="41" cy="50" rx="10" ry="5"/><ellipse cx="59" cy="50" rx="10" ry="5"/></g><circle cx="50" cy="50" r="5" fill="#20372f"/>':'<circle cx="50" cy="50" r="6" fill="currentColor"/><path d="M55 40 Q69 28 68 40 Q64 50 55 48Z" fill="currentColor" opacity=".65"/>';return `<svg viewBox="0 0 100 100" aria-hidden="true"><path d="${paths}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>${center}</svg>`;}
function render(){const lit=connected(tiles,puzzle.n,puzzle.source);board.style.setProperty('--size',puzzle.n);tiles.forEach((mask,i)=>{const b=board.children[i];b.className=`tile ${lit.has(i)?'lit':''} ${i===puzzle.source?'source':''} ${i===highlight?'hinted':''}`;b.innerHTML=tileArt(mask,i);const directions=['up','right','down','left'].filter((_,d)=>mask&(1<<d)).join(', ');b.setAttribute('aria-label',`Row ${Math.floor(i/puzzle.n)+1}, column ${i%puzzle.n+1}, ${i===puzzle.source?'golden seed, ':''}${lit.has(i)?'glowing':'unlit'}, branches ${directions}. Rotate clockwise`);});$('lit').textContent=`${lit.size} / ${tiles.length}`;$('moves').textContent=moves;$('undo').disabled=!history.length||won;$('hint').disabled=won;$('level-label').textContent=`GROVE ${String(save.index+1).padStart(2,'0')} / 24`;$('level-name').textContent=names[save.index];$('chapter-number').textContent=String(Math.floor(save.index/6)+1).padStart(2,'0');$('chapter-name').textContent=chapters[Math.floor(save.index/6)];$('chapter-dots').innerHTML=Array.from({length:6},(_,i)=>`<i class="${save.results[Math.floor(save.index/6)*6+i]?'done':''}"></i>`).join('');const count=Object.keys(save.results).length;$('completed').textContent=`${count} of 24 groves restored`;$('progress').style.width=`${count/24*100}%`;$('stars').textContent=`✦ ${Object.values(save.results).reduce((a,b)=>a+b,0)}`;}
function openDialog(html){$('dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal();}
function finish(){won=true;const stars=hints?1:moves<=puzzle.par?3:2;save.results[save.index]=Math.max(save.results[save.index]||0,stars);render();tone(true);openDialog(`<div class="big-symbol">${'✦'.repeat(stars)}</div><div class="eyebrow">GROVE RESTORED</div><h2>${Object.keys(save.results).length===COUNT?'A world brought to light.':'Look at you grow.'}</h2><p>Every branch is glowing. You restored this grove in ${moves} turns${hints?` with ${hints} hint${hints===1?'':'s'}`:''}.</p><p>Earn three stars with no hints in ${puzzle.par} turns or fewer. Two stars for any unassisted solve.</p><button class="primary" id="next">${save.index===COUNT-1?'Explore your groves':'Grow the next grove →'}</button>`);$('next').onclick=()=>{dialog.close();if(save.index===COUNT-1)showLevels();else start(save.index+1);};}
function turn(i){if(won||paused||systemPaused||dialog.open)return;history.push({tiles:[...tiles],moves,hints});tiles[i]=rotate(tiles[i]);moves++;highlight=-1;render();tone();if(connected(tiles,puzzle.n,puzzle.source).size===tiles.length)finish();persist();}
function start(index,resume=false){save.index=index;puzzle=level(index);tiles=resume&&save.active?[...save.active.tiles]:[...puzzle.tiles];moves=resume&&save.active?save.active.moves:0;hints=resume&&save.active?save.active.hints:0;history=[];highlight=-1;won=false;board.replaceChildren();tiles.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.onclick=()=>turn(i);b.onkeydown=e=>{const d={ArrowUp:-puzzle.n,ArrowDown:puzzle.n,ArrowLeft:-1,ArrowRight:1}[e.key];if(d!==undefined){e.preventDefault();board.children[(i+d+tiles.length)%tiles.length].focus();}};board.append(b);});$('instruction').textContent='Tap a tile to rotate it. Connect every tile to the golden seed.';render();if(connected(tiles,puzzle.n,puzzle.source).size===tiles.length)finish();if(!resume)persist();}
function showLevels(){openDialog(`<div class="eyebrow">YOUR LITTLE WORLD</div><h2>Explore the grove</h2><p>24 quiet puzzles. Pick a path, or return to earn more stars.</p><div class="level-grid">${Array.from({length:COUNT},(_,i)=>`<button data-level="${i}" class="${save.results[i]?'finished':''} ${i===save.index?'current':''}" aria-label="Grove ${i+1}, ${save.results[i]||0} stars">${String(i+1).padStart(2,'0')}<small>${save.results[i]?'✦'.repeat(save.results[i]):'·'}</small></button>`).join('')}</div>`);dialog.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{dialog.close();start(Number(b.dataset.level));});}
$('levels').onclick=showLevels;
$('help').onclick=()=>openDialog('<div class="big-symbol">✧</div><div class="eyebrow">LET IT BLOOM</div><h2>A little light goes a long way.</h2><ol><li>The golden seed is your source of light.</li><li>Tap any tile to turn its branches clockwise.</li><li>Join matching branches. Connected tiles glow and flowers bloom.</li><li>Light every tile to restore the grove.</li></ol><p>Use Tab or arrow keys to move between tiles, and Enter or Space to rotate. Undo a turn, restart, or use a hint whenever you like. There is no time limit.</p><p>Three stars: no hints and within the target turns. Two: finish without hints. One: finish with hints.</p>');
$('close-dialog').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{paused=false;document.body.classList.toggle('paused',systemPaused);});
$('pause').onclick=()=>{paused=true;context?.suspend();document.body.classList.add('paused');openDialog('<div class="big-symbol">☾</div><h2>Take a breath.</h2><p>Your garden will be right here.</p><button class="primary" id="resume">Back to the grove</button>');$('resume').onclick=()=>dialog.close();persist();};
$('undo').onclick=()=>{if(!history.length||won||systemPaused)return;const last=history.pop();tiles=last.tiles;moves=last.moves;hints=last.hints;highlight=-1;render();persist();};
$('restart').onclick=()=>{if(systemPaused)return;openDialog('<h2>A fresh start?</h2><p>Restart this puzzle from its original arrangement. Your earned stars stay safe.</p><button class="primary" id="confirm-restart">Restart this grove</button>');$('confirm-restart').onclick=()=>{dialog.close();start(save.index);};};
$('hint').onclick=()=>{if(won||systemPaused)return;const i=tiles.findIndex((v,i)=>v!==puzzle.solution[i]);if(i<0)return;history.push({tiles:[...tiles],moves,hints});tiles[i]=puzzle.solution[i];hints++;moves++;highlight=i;render();$('instruction').textContent='The outlined branch is now facing the right way.';if(connected(tiles,puzzle.n,puzzle.source).size===tiles.length)finish();persist();};
$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Disable sound effects':'Enable sound effects');$('sound').innerHTML=`♪ <span>Sound ${sound?'on':'off'}</span>`;if(!sound)context?.suspend();else tone();};if(embedded)$('sound').hidden=true;
platform.firstFrame();platform.bind({pause:()=>{persist();systemPaused=true;document.body.classList.add('paused');document.querySelector('main').inert=true;document.querySelector('header').inert=true;dialog.inert=true;context?.suspend();},resume:()=>{systemPaused=false;document.body.classList.toggle('paused',paused);document.querySelector('main').inert=false;document.querySelector('header').inert=false;dialog.inert=false;},audio:enabled=>{audioAllowed=enabled;if(!enabled)context?.suspend();}});
save=validateSave(await platform.load());start(save.index,true);$('loading').hidden=true;platform.ready();
